### PR TITLE
Rename files to support OSX case insensitive FS

### PR DESCRIPTION
**Pull request by baer**
I've run into a lot of frustrating git tree manipulation on account of OSX's (nearly) mandatory case insensitive FS. To avoid these issues in the future it may be better to set the standard of dashes instead of bumpy case for file naming.

### CODE REVIEW

**Comment by patrickkettner** [comment]
eh.... I am leaning towards :-1:, mostly just because JS is camelCase, python is kebab-case.

what is the number of issues you have run into?

**Comment by patrickkettner** [comment]
also, have you tried

```
git mv filename filename.bak
git mv filename.bak fileName
```

**Comment by baer** [comment]
BumpyCase + OSX is a potential footgun but it's easily avoided. I've seen stuff like mistakenly naming a file `MyFile.js` then trying to rename to `myFile.js`which will cause both files to live in the tree. It's not a big deal if you keep tight reins on the code but kebab case for file names is just a little less error prone.

I like `git mv` and since this is a small OSS project you can close this PR out if you don't think this will be an issue.

**Comment by patrickkettner** [comment]
there are just so few files I don't think this will be an issue here.

appreciate the idea, however

**Pull request closed without merging**
