### PR TITLE
Update lodash

### PR DESCRIPTION
**Pull request by baer**
'nuff said

### CODE REVIEW

**Comment by patrickkettner** [comment]
Lgtm

Any reason othe than shiney shiney?

**Comment by baer** [comment]
Nope, just happened to notice it was out of date. Can't have a library that checks other people's dependency drift that has version drift.

**Comment by patrickkettner** [comment]
Haha. Ever check out David?

**Comment by baer** [comment]
No. What's that?

**Comment by patrickkettner** [comment]
https://github.com/alanshaw/david

Deep dep updater

**Pull request merged**
