### PR TITLE
Correct bad example config in the docs

### PR DESCRIPTION
**Pull request by baer**
I was wondering why the outer krabby was required and it turns out it's not :)

### CODE REVIEW

**Comment by patrickkettner** [comment]
it is for `package.json`

**Comment by baer** [comment]
Ahhh, yea that makes sense. What if I move the krabby.json vs package.json section up above the config to make that clear? Or even a little disclaimer?

**Comment by patrickkettner** [comment]
I don't really see much of a point, honestly. it would just be duplicated noise, when both are supported. a note saying it isn't necessary for a `krabby.json` file, maybe?

**Comment by baer** [comment]
Another 2 options:
I could also modify those two examples to make it clear that it's a package.json file. I can't remember if github lets you label the code sections but I'm sure we could figure it out.

OR 

I can just fix the index.js to handle either case

**Comment by patrickkettner** [comment]
index.js should already handle both cases - how does it not?

**Comment by patrickkettner** [comment]
could you break out the report from the docs change?

**Comment by baer** [comment]
Woah, lots of code committed here that was not intended to go up! Sorry about that.

**Comment by patrickkettner** [comment]
sall good :]

**Pull request closed without merging**
